apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
  labels:
    app: myapp
    type: front-end
# This template required for Pod creation
spec:
  template:
    metadata:
      name: myapp-pod
      labels:
        app: myapp
        type: front-end
    spec:
      containers:
        - name: nginx-container
          image: nginx
replicas: 3
#selector uses here to identify his own pod
selector:
   matchLabels:
      type: front-end

# Use below cmd for run
# kubectl create -f deployment-definition.yaml

# kubectl get deployment
#kubectl get replicaset      (this is auto created by deployment)

# kubectl get pods

# To scale up/down of replicas following is the cmd
# kubectl replace -f replicaset-definition.yaml
# kubectl scale --replicas=6 -f replicaset-definition.yaml
# kubectl scale --replicas=6 replicaset(type) myapp-replicaset(name)