apiVersion: v1
kind: Service
metadata:
  name: myapp-service
  
# This template required for Pod creation
spec:
  type: NodePort
  ports:
    - targetPort: 80
      port: 80
      nodeport: 30008

  selector:
      app: myapp
      type: front-end

# Use below cmd for run
# kubectl create -f ndservice-definition.yaml

# kubectl get services
# curl http://192.168.1.2:30008
# minikube service myapp-service --url

# kubectl get pods

# To scale up/down of replicas following is the cmd
# kubectl replace -f replicaset-definition.yaml
# kubectl scale --replicas=6 -f replicaset-definition.yaml
# kubectl scale --replicas=6 replicaset(type) myapp-replicaset(name)